### ISSUE TITLE
ImportError: No module named 'sso'

### ISSUE THREAD

**Issue by andreypilyugin** [uservoice/uservoice-python#4]
Mac OS 10.10
Python 3.4

---------------
1. I installed uservoice as described here (https://github.com/uservoice/uservoice-python):
    pip install uservoice
2. Simple "import uservoice" fires error:
    Traceback (most recent call last): 
    File "<stdin>", line 1, in <module> 
    File "python3.4/site-packages/uservoice/__init__.py", line 1, in <module> 
    from sso import generate_sso_token 
    ImportError: No module named 'sso'

**Comment by austintaylor** [comment]
Well, crap. It seems this project was written against Python 2 and never updated. The immediate issue is that those imports need to be explicitly relative. There could be other compatibility issues as well. I'll see if I can get the tests running with Python 3.

**Comment by austintaylor** [comment]
Ok, please try again with 0.0.20. Tests now pass under both Python 2 and 3.
