### ISSUE TITLE
Choose a license for this package

### ISSUE THREAD

**Issue by eli-b** [uservoice/uservoice-python#6]
Please specify a license in the package's setup.py.
I was told on Oct 30, 2015 that the package is licensed under the MIT license, but still nothing in the package states that.

**Comment by flebel** [comment]
https://github.com/uservoice/uservoice-python/blob/822c1f8c051571a59c2bb7028bd5221237a6ac8d/setup.py#L15

**Comment by eli-b** [comment]
Thanks a lot!
